#cloud-config
hostname: <HOSTNAME>
ssh-authorized-keys:
- <PUBLIC-KEY>
coreos:
    units:
        # turn off automatic updates
        - name: update-engine.service
          command: stop
        - name: locksmithd.service
          command: stop
        - name: 01-eth0.network
          runtime: true
          content: |
            [Match]
            Name=eth0

            [Network]
            DNS=8.8.8.8
        - name: etcd2.service
          command: start
        - name: fleet.service
          command: start
    etcd2:
        name: "<HOSTNAME>"
        initial-cluster: "<HOSTNAME>=http://<PUBLIC_IP>:2380"
        initial-cluster-state: "new"
        # multi-region and multi-cloud deployments need to use $public_ipv4
        advertise-client-urls: "http://<PUBLIC_IP>:2379"
        initial-advertise-peer-urls: "http://<PUBLIC_IP>:2380"
        # listen on both the official ports and the legacy ports
        # legacy ports can be omitted if your application doesn't depend on them
        listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
        listen-peer-urls: "http://0.0.0.0:2380"
    fleet:
        metadata: "region=de"
        public-ip: "<PUBLIC_IP>"
